sudo: required
language: php
before_install:
  - nvm install node && nvm use node
  - npm install -g dredd --no-optional
  - bundle install
  - composer install
php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7"
  - "7.1"
  - "7.2"
script:
  - dredd laravel.apib http://localhost:8001 --server "php -S 0.0.0.0:8001 -t public/" --language vendor/bin/dredd-hooks-php --hookfiles tests/dredd/hooks/hookfile.php
  - bundle exec cucumber
